-
  branches:
    only:
      - master

  artifacts:
    path: 'RestSharp\bin\Release\*.nupkg'

  configuration: Release

  image: Visual Studio 2017

  build_script:
    - build.bat

  skip_tags: true

-
  branches:
    only:
      - develop

  artifacts:
    path: 'RestSharp\bin\Debug\*.nupkg'

  configuration: Debug

  image: Visual Studio 2017

  build_script:
    - build.bat

  skip_tags: true

-
  configuration: Debug

  image: Visual Studio 2017

  build_script:
    - build.bat

  skip_tags: true

